package com.gexiiiii.gfood.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gexiiiii.gfood.bean.db.FavoriteMenuBean;
import com.gexiiiii.gfood.bean.db.FavoriteNewsBean;
import com.gexiiiii.gfood.bean.db.NoteBean;
import com.gexiiiii.gfood.bean.db.LookHistoryBean;
import com.gexiiiii.gfood.bean.db.SearchHistoryBean;

import com.gexiiiii.gfood.greendao.FavoriteMenuBeanDao;
import com.gexiiiii.gfood.greendao.FavoriteNewsBeanDao;
import com.gexiiiii.gfood.greendao.NoteBeanDao;
import com.gexiiiii.gfood.greendao.LookHistoryBeanDao;
import com.gexiiiii.gfood.greendao.SearchHistoryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteMenuBeanDaoConfig;
    private final DaoConfig favoriteNewsBeanDaoConfig;
    private final DaoConfig noteBeanDaoConfig;
    private final DaoConfig lookHistoryBeanDaoConfig;
    private final DaoConfig searchHistoryBeanDaoConfig;

    private final FavoriteMenuBeanDao favoriteMenuBeanDao;
    private final FavoriteNewsBeanDao favoriteNewsBeanDao;
    private final NoteBeanDao noteBeanDao;
    private final LookHistoryBeanDao lookHistoryBeanDao;
    private final SearchHistoryBeanDao searchHistoryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteMenuBeanDaoConfig = daoConfigMap.get(FavoriteMenuBeanDao.class).clone();
        favoriteMenuBeanDaoConfig.initIdentityScope(type);

        favoriteNewsBeanDaoConfig = daoConfigMap.get(FavoriteNewsBeanDao.class).clone();
        favoriteNewsBeanDaoConfig.initIdentityScope(type);

        noteBeanDaoConfig = daoConfigMap.get(NoteBeanDao.class).clone();
        noteBeanDaoConfig.initIdentityScope(type);

        lookHistoryBeanDaoConfig = daoConfigMap.get(LookHistoryBeanDao.class).clone();
        lookHistoryBeanDaoConfig.initIdentityScope(type);

        searchHistoryBeanDaoConfig = daoConfigMap.get(SearchHistoryBeanDao.class).clone();
        searchHistoryBeanDaoConfig.initIdentityScope(type);

        favoriteMenuBeanDao = new FavoriteMenuBeanDao(favoriteMenuBeanDaoConfig, this);
        favoriteNewsBeanDao = new FavoriteNewsBeanDao(favoriteNewsBeanDaoConfig, this);
        noteBeanDao = new NoteBeanDao(noteBeanDaoConfig, this);
        lookHistoryBeanDao = new LookHistoryBeanDao(lookHistoryBeanDaoConfig, this);
        searchHistoryBeanDao = new SearchHistoryBeanDao(searchHistoryBeanDaoConfig, this);

        registerDao(FavoriteMenuBean.class, favoriteMenuBeanDao);
        registerDao(FavoriteNewsBean.class, favoriteNewsBeanDao);
        registerDao(NoteBean.class, noteBeanDao);
        registerDao(LookHistoryBean.class, lookHistoryBeanDao);
        registerDao(SearchHistoryBean.class, searchHistoryBeanDao);
    }
    
    public void clear() {
        favoriteMenuBeanDaoConfig.clearIdentityScope();
        favoriteNewsBeanDaoConfig.clearIdentityScope();
        noteBeanDaoConfig.clearIdentityScope();
        lookHistoryBeanDaoConfig.clearIdentityScope();
        searchHistoryBeanDaoConfig.clearIdentityScope();
    }

    public FavoriteMenuBeanDao getFavoriteMenuBeanDao() {
        return favoriteMenuBeanDao;
    }

    public FavoriteNewsBeanDao getFavoriteNewsBeanDao() {
        return favoriteNewsBeanDao;
    }

    public NoteBeanDao getNoteBeanDao() {
        return noteBeanDao;
    }

    public LookHistoryBeanDao getLookHistoryBeanDao() {
        return lookHistoryBeanDao;
    }

    public SearchHistoryBeanDao getSearchHistoryBeanDao() {
        return searchHistoryBeanDao;
    }

}
