package com.gexiiiii.gfood.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.gexiiiii.gfood.bean.db.FavoriteMenuBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "tb_favorite_menu".
*/
public class FavoriteMenuBeanDao extends AbstractDao<FavoriteMenuBean, String> {

    public static final String TABLENAME = "tb_favorite_menu";

    /**
     * Properties of entity FavoriteMenuBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Tags = new Property(2, String.class, "tags", false, "TAGS");
        public final static Property Imtro = new Property(3, String.class, "imtro", false, "IMTRO");
        public final static Property Ingredients = new Property(4, String.class, "ingredients", false, "INGREDIENTS");
        public final static Property Burden = new Property(5, String.class, "burden", false, "BURDEN");
        public final static Property Albums = new Property(6, String.class, "albums", false, "ALBUMS");
    }


    public FavoriteMenuBeanDao(DaoConfig config) {
        super(config);
    }
    
    public FavoriteMenuBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"tb_favorite_menu\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"TAGS\" TEXT," + // 2: tags
                "\"IMTRO\" TEXT," + // 3: imtro
                "\"INGREDIENTS\" TEXT," + // 4: ingredients
                "\"BURDEN\" TEXT," + // 5: burden
                "\"ALBUMS\" TEXT);"); // 6: albums
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"tb_favorite_menu\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FavoriteMenuBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(3, tags);
        }
 
        String imtro = entity.getImtro();
        if (imtro != null) {
            stmt.bindString(4, imtro);
        }
 
        String ingredients = entity.getIngredients();
        if (ingredients != null) {
            stmt.bindString(5, ingredients);
        }
 
        String burden = entity.getBurden();
        if (burden != null) {
            stmt.bindString(6, burden);
        }
 
        String albums = entity.getAlbums();
        if (albums != null) {
            stmt.bindString(7, albums);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FavoriteMenuBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(3, tags);
        }
 
        String imtro = entity.getImtro();
        if (imtro != null) {
            stmt.bindString(4, imtro);
        }
 
        String ingredients = entity.getIngredients();
        if (ingredients != null) {
            stmt.bindString(5, ingredients);
        }
 
        String burden = entity.getBurden();
        if (burden != null) {
            stmt.bindString(6, burden);
        }
 
        String albums = entity.getAlbums();
        if (albums != null) {
            stmt.bindString(7, albums);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public FavoriteMenuBean readEntity(Cursor cursor, int offset) {
        FavoriteMenuBean entity = new FavoriteMenuBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tags
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // imtro
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ingredients
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // burden
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // albums
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FavoriteMenuBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTags(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImtro(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIngredients(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBurden(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAlbums(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final String updateKeyAfterInsert(FavoriteMenuBean entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(FavoriteMenuBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FavoriteMenuBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
